local tbl_merges = require('mug.module.util').tbl_merges

---@class tbl
---@field positions table
---@field plugins table
---@field modules table
---@field options table
local M = {}

M.positions = {
  top = 'aboveleft ',
  bottom = 'belowright ',
  left = 'vertical aboveleft ',
  right = 'vertical belowright ',
}

M.plugins = {
  'commit',
  'conflict',
  'diff',
  'files',
  'index',
  'merge',
  'mkrepo',
  'rebase',
  'show',
  'subcommand',
  'terminal',
}

M.modules = {
  'mug',
  'mug.module.comp',
  'mug.module.extmark',
  'mug.module.float',
  'mug.module.highlight',
  'mug.module.job',
  'mug.module.map',
  'mug.module.shell',
  'mug.module.table',
  'mug.module.timer',
  'mug.module.util',
  'mug.branch',
  'mug.commit',
  'mug.config',
  'mug.conflict',
  'mug.diff',
  'mug.files',
  'mug.index',
  'mug.merge',
  'mug.mkrepo',
  'mug.patch',
  'mug.rebase',
  'mug.terminal',
  'mug.show',
  'mug.subcommand',
  'mug.workspace',
}

M.options = {
  'float_winblend',
  'symbol_not_repository',
  'edit_command',
  'file_command',
  'write_command',
  'strftime',
  'commit_notation',
  'commit_gpg_sign',
  'conflict_begin',
  'conflict_anc',
  'conflict_sep',
  'conflict_end',
  'filewin_beacon',
  'filewin_indicates_position',
  'loclist_position',
  'loclist_disable_column',
  'diff_position',
  'index_add_key',
  'index_force_key',
  'index_reset_key',
  'index_clear_key',
  'index_inputbar',
  'index_commit',
  'index_auto_update',
  'remote_url',
  'commit_initial_msg',
  'show_command',
  'sub_command',
  'term_command',
  'term_height',
  'term_width',
  'term_shell',
  'term_position',
  'term_disable_columns',
  'term_nvim_pseudo',
  'term_nvim_opener',
  'patch_window_height',
  'result_position',
  'result_log_format',
  'result_map',
}

M.sub_commands = {
  'clone',
  'init',
  'add',
  'mv',
  'restore',
  'bisect',
  'diff',
  'grep',
  'log',
  'show',
  'stash',
  'status',
  'branch',
  'commit',
  'rebase',
  'reset',
  'switch',
  'tag',
  'fetch',
  'pull',
  'push',
  'cherry-pick',
  'revert',
}

M.clone_options = {
  '--verbose',
  '--progress',
  '--reject-shallow',
  '--no-checkout',
  '--bare',
  '--mirror',
  '--no-hardlinks',
  '--shared',
  '--recurse-submodules=',
  '--jobs=',
  '--template=',
  '--reference=',
  '--reference-if-able=',
  '--dissociate',
  '--origin=',
  '--branch=',
  '--upload-pack=',
  '--depth=',
  '--shallow-since=',
  '--shallow-exclude=',
  '--single-branch',
  '--shallow-submodules',
  '--no-tags',
  '--separate-git-dir=',
  '--config',
  '--server-option=',
  '--ipv4',
  '--ipv6',
  '--filter=',
  '--also-filter-submodules',
  '--remote-submodules',
  '--sparse',
}

M.init_options = {
  '--template=',
  '--bare',
  '--shared',
  '--separate-git-dir=',
  '--initial-branch=',
}

M.add_options = {
  '--dry-run',
  '--verbose',
  '--interactive',
  '--patch',
  '--edit',
  '--force',
  '--update',
  '--renormalize',
  '--intent-to-add',
  '--all',
  '--refresh',
  '--ignore-errors',
  '--ignore-missing',
  '--sparse',
  '--chmode=',
  '--pathspec-from-file=',
  '--pathspec-file-nul',
}

M.mv_options = {
  '--dry-run',
  '--verbose',
  '--force',
  '--sparse',
}

M.rm_options = {
  '--dry-run',
  '--cached',
  '--force',
  '--sparse',
  '--ignore-unmatch',
  '--pathspec-from-file=',
  '--pathspec-file-nul',
}

M.restore_options = {
  '--source=',
  '--staged',
  '--worktree',
  '--ignore-unmerged',
  '--overlay',
  '--recurse-submodules',
  '--progress',
  '--merge',
  '--conflict=merge',
  '--conflict=diff3',
  '--ours',
  '--theirs',
  '--patch',
  '--ignore-skip-worktree-bits',
  '--pathspec-from-file=',
  '--paathspec-file-nul',
}

M.bisect_options = {
  'help',
  'start',
  'bad',
  'good',
  'terms',
  'skip',
  'next',
  'reset',
  'view',
  'replay',
  'log',
  'run',
}

M.diff_options = {
  '--no-patch',
  '--unified=',
  '--output=',
  '--function-context',
  '--raw',
  '--patch-with-raw',
  '--patch-with-stat',
  '--numstat',
  '--shortstat',
  '--dirstat',
  '--cumulative',
  '--check',
  '--summary',
  '--name-only',
  '--name-status',
  '--stat',
  '--compact-summary',
  '--binary',
  '--full-index',
  '--ws-error-highlight=',
  '--abbrev',
  '--no-prefix',
  '--inter-hunk-context=',
  '--break-rewrites',
  '--find-renames',
  '--irreversible-delete',
  '--find-copies',
  '--find-copies-harder',
  '--no-renames',
  '--rename-empty',
  '--follow',
  '--minimal',
  '--ignore-all-space',
  '--ignore-space-change',
  '--ignore-space-at-eol',
  '--ignore-blank-lines',
  '--ignore-matching-lines',
  '--indent-heuristic',
  '--patience',
  '--histogram',
  '--diff-algorithm=patience',
  '--diff-algorithm=minimal',
  '--diff-algorithm=heuristic',
  '--diff-algorithm=default',
  '--anchored=',
  '--word-diff',
  '--word-diff-regex=',
  '--color-moved',
  '--color-moved-ws',
  '--no-color-moved',
  '--relative',
  '--text',
  '--exit-code',
  '--ext-diff',
  '--textconv',
  '--ignore-submodules',
  '--submodule',
  '--pickaxe-all',
  '--pickaxe-regex',
  '--find-object=',
  '--diff-filter=',
}

M.grep_options = {
  '--cached',
  '--no-index',
  '--untracked',
  '--no-exclude-standard',
  '--recurse-submodules',
  '--invert-match',
  '--ignore-case',
  '--word-regexp',
  '--text',
  '--textconv',
  '--recursive',
  '--max-depth',
  '--extended-regexp',
  '--basic-regexp',
  '--fixed-strings',
  '--perl-regexp',
  '--line-number',
  '--column',
  '--full-name',
  '--name-only',
  '--files-with-matches',
  '--files-without-match',
  '--only-matching',
  '--count',
  '--break',
  '--heading',
  '--context=',
  '--before-context=',
  '--after-context=',
  '--therads',
  '--show-function',
  '--function-context',
  '--and',
  '--or',
  '--not',
  '-all-match',
  '--open-files-in-pager',
  '--max-count=',
}

local log = {
  '--full-diff',
  '--log-size',
  '--skip',
  '--since',
  '--until',
  '--author=',
  '--grep-reflog=',
  '--grep=',
  '--all-match',
  '--invert-grep',
  '--regexp-ignore-case',
  '--basic-regexp',
  '--extended-regexp',
  '--perl-regexp',
  '--remove-empty',
  '--merges',
  '--no-merges',
  '--min-parents=',
  '--max-parents=',
  '--first-parent',
  '--not',
  '--all',
  '--branches',
  '--tags',
  '--remotes',
  '--glob=',
  '--exclude=',
  '--reglog',
  '--alternate-regs',
  '--single-worktree',
  '--ignore-missing',
  '--bisect',
  '--stdin',
  '--cherry-mark',
  '--left-only',
  '--right-only',
  '--cherry',
  '--wark-reflogs',
  '--merge',
  '--boundary',
  '--simplify-by-decoration',
  '--show-pulls',
  '--full-history',
  '--dense',
  '--sparse',
  '--simplify-merges',
  '--ancestry-path',
  '--date-order',
  '--author-date-order',
  '--topo-order',
  '--reverse',
  '--no-walk',
  '--date=short',
  '--date=raw',
  '--date=unix',
  '--date=human',
  '--date=iso',
  '--parents',
  '--children',
  '--left-right',
  '--graph',
  '--cc',
  '--combined-all-paths',
  '--no-diff-merges',
  '--patch',
}

local show = {
  '--source',
  '--use-mailmap',
  '--mailmap',
  '--no-decorate',
  '--decorate=full',
  '--decorate-refs=',
  '--decorate-regs-exclude=',
  '--format=',
  '--abbrev-commit',
  '--oneline',
  '--encoding=',
  '--expand-tabs',
  '--no-notes',
  '--show-signature',
}

M.log_options = tbl_merges(log, show, M.diff_options)
M.show_options = vim.list_extend(show, M.diff_options)

M.status_options = {
  '--verbose',
  '--short',
  '--branch',
  '--show-stash',
  '--no-ahead-behind',
  '--porcelain',
  '--long',
  '--untracked-files',
  '--inored',
  '--ignore-submodules',
  '--column',
  '--no-renames',
  '--find-renames',
}

M.branch_options = {
  '--verbose',
  '--all',
  '--delete',
  '--move',
  '--copy',
  '--list',
  '--show-current',
  '--create-reflog',
  '--edit-description',
  '--force',
  '--merged=',
  '--no-merged=',
  '--column',
  '--sort=',
  '--points-at=',
  '--ignore-case',
  '--recurse-submodules',
  '--format',
}

M.commit_options = {
  '--verbose',
  '--file=',
  '--author=',
  '--date=',
  '--message=',
  '--reuse-message=',
  '--reedit-message=',
  '--fixup=',
  '--squash=',
  '--reset-author',
  '--trailer=',
  '--signoff',
  '--template=',
  '--edit',
  '--cleanup=',
  '--no-status',
  '--gpg-sign',
  '--all',
  '--include',
  '--patch',
  '--only',
  '--no-verify',
  '--dry-run',
  '--short',
  '--branch',
  '--ahead-behind',
  '--porcelain',
  '--long',
  '--allow-empty',
  '--allow-empty-message',
  '--amend',
  '--no-post-rewrite',
  '--pathspec-from-file',
  '--pathspec-file-nul',
  '--untracked-files',
}

local merge = {
  '--stat',
  '--log',
  '--squash',
  '--comit',
  '--edit',
  '--cleanup=',
  '--ff',
  '--ff-only',
  '--verify-signatures',
  '--strategy=',
  '--strategy-option=',
  '--allow-unrelated-histories',
  '--gpq-sign=',
  '--autostash',
  '--signoff',
  '--no-verify',
}

M.merge_options = vim.list_extend(merge, {
  '--summary',
  '--file=',
  '--message',
  '--rerere-autoupdate',
  '--no-overwrite-ignore',
})

M.rebase_options = {
  '--verbose',
  '--onto',
  '--keep-base',
  '--no-verify',
  '--stat',
  '--no-stat',
  '--signoff',
  '--committer-date-is-author-date',
  '--reset-author-date',
  '--ignore-whitespace',
  '--whitespace=',
  '--force-rebase',
  '--no-ff',
  '--apply',
  '--merge',
  '--interactive',
  '--rerere-autoupdate',
  '--empty=drop',
  '--empty=keep',
  '--empty=ask',
  '--no-keep-empty',
  '--autosquash',
  '--update-refs',
  '--gpq-sign',
  '--autostash',
  '--exec',
  '--rebase-merges=rebase-cousins',
  '--fork-point',
  '--no-fork-point',
  '--strategy=',
  '--strategy-option=',
  '--root',
  '--reschedule-failed-exec',
  '--reapply-cherry-picks',
  '--allow-empty-message',
}

M.reset_options = {
  '--no-refresh',
  '--soft',
  '--mixed',
  '--hard',
  '--merge',
  '--keep',
  '--recurse-submodules',
  '--patch',
  '--intent-to-add',
  '--pathspec-from-file',
  '--pathspec-file-nul',
}

M.switch_options = {
  '--create',
  '--force-create',
  '--guess',
  'discard-changes',
  '--recurse-submodules',
  '--progress',
  '--merge',
  '--detach',
  '--conflict=diff3',
  '--track',
  '--force',
  '--orphan',
  '--overwrite-ignore',
  '--ignore-other-worktrees',
}

M.stash_options = {
  'list',
  'show',
  'drop',
  'pop',
  'apply',
  'branch',
  'push',
  'save',
  'clear',
  'store',
}

M.tag_options = {
  '--list',
  '--delete',
  '--verify',
  '--annotate',
  '--message=',
  '--file=',
  '--edit',
  '--sign',
  '--cleanup=',
  '--local-user=',
  '--force',
  '--create-reflog',
  '--column',
  '--contains',
  '--merged',
  '--sort=',
  '--points-at',
  '--format=',
  '--ignore-case',
}

local fetch = {
  '--verbose',
  '--all',
  '--set-upstream',
  '--append',
  '--upload-pack',
  '--force',
  '--tags',
  '--jobs=',
  '--prune',
  '--recurse-submodules',
  '--dry-run',
  '--keep',
  '--progress',
  '--depth=',
  '--shallow-since=',
  '--shallow-exclude',
  '--deepen=',
  '--unshallow',
  '--update-shallow',
  '--refmap=',
  '--server-option=',
  '--negotiation-tip=commit',
  '--negotiation-tip=glob',
  '--no-tags',
  '--show-forced-updates',
  '--ipv4',
  '--ipv6',
}

M.fetch_options = tbl_merges(fetch, {
  '--atomic',
  '--prune-tags',
  '--prefetch',
  '--refetch',
  '--multiple',
  '--no-auto-maintenance',
  '--write-commit-graph',
  '--write-fetch-head',
  '--submodule-prefix=',
  '--update-head-ok',
})

local pull = {
  '--rebase',
}

M.pull_options = tbl_merges(fetch, merge, pull)

M.push_options = {
  '--verbose',
  'recurse-submodules',
  '--all',
  '--prune',
  '--mirror',
  '--dry-run',
  '--porcelain',
  '--delete',
  '--tags',
  '--follow-tags',
  '--signed=if-asked',
  '--atomic',
  '--push-option=',
  '--force-with-lease=',
  '--repo',
  '--set-upstream',
  '--no-verify',
  '--ipv4',
  '--ipv6',
}

M['cherry-pick'] = {
  '--edit',
  '--strategy-option',
  '--gpg-sign',
  '--ff',
  '--allow-empty',
  '--allow-empty-message',
  '--keep-redundant-commits',
}

M.revert_options = {
  '--cleanup',
  '--no-commit',
  '--edit',
  '--signoff',
  '--mainline',
  '--rerere-autoupdate',
  '--strategy-option',
  '--gpg-sign',
  '--reference',
}

return M
